name: check-parser

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            triple: x86_64-linux-gnu
          - name: macos-latest
            triple: arm64-apple-darwin
          - name: macos-13
            triple: x86_64-apple-darwin
          
      fail-fast: false
    runs-on: ${{ matrix.os.name }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: setup moon
        uses: illusory0x0/setup-moonbit@v0.1.0
        with: 
          version: stable

      - name: install module dependencies
        run: |
          moon update
          moon install

      - name: moon check
        run: moon check --deny-warn

      - name: test
        run: |
          cd $GITHUB_WORKSPACE
          python3 .github/scripts/ci_parser.py
